# Repo: helm install kiwigrid/fluentd-elasticsearch
# Chart: kiwigrid/fluentd-elasticsearch
# Git: https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch
---
elasticsearch:
  host: elasticsearch-master

configMaps:
  useDefaults:
    containersInputConf: false

additionalPlugins:
  - name: fluent-plugin-docker_metadata_elastic_filter
    version: 0.2.1

extraVolumeMounts:
  - name: dockersock
    mountPath: "/var/run/docker.sock"
    readOnly: true

extraVolumes: 
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock

tolerations:
- key: com.docker.ucp.manager
  operator: Exists
  effect: NoSchedule
  

extraConfigMaps:
  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    <source>
      @type tail
      path /var/lib/docker/containers/*/*-json.log
      pos_file fluentd-docker.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag raw.swarm.*
      format json
      read_from_head true
    </source>

    <match raw.swarm.**>
      @id raw.swarm
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    # Fixes json fields in Elasticsearch
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    <filter swarm.**>
      @type docker_metadata_elastic
    </filter>

    <filter swarm.**>
      @type grep
      <exclude>
        key docker.name
        key $.docker.name
        pattern /k8s_/
      </exclude>
    </filter>
